typography_spectrum: 0.3636919145938009
content_rating:
  adult: false
color:
  brandColors:
    - '#7D8A2E'
    - '#C9D787'
    - '#FFFFFF'
    - '#FFC0A9'
    - '#FF8598'
  brandStrength: 0.37090283329598606
  lightness: 0.3438636993523687
  saturation: 0.8403489671181887
  rhythmicContrast: 0.5562360014300793
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.9339640869293362
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: John De Mello
  email: john.dtgworks@gmail.com
  url: www.dtgworks.com
logo: null
name: 'DTG works '
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/bbeedef5-d7a5-4a40-9055-2d98f523bfe6.jpg
title: ''
purpose: []
