typography_spectrum: 0.48961
content_rating:
  adult: false
color:
  brandColors:
    - '#4d555d'
    - '#8c9dad'
    - '#171a20'
    - '#c0c9d5'
    - '#914858'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.36565
analytics:
  google: null
  facebook: null
  twitter: null
logo: null
name: 'DTG works '
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: ''
purpose: []
