name: DTG works
favicon: null
layout_spectrum: 0.1083
typography_spectrum: 0.60432
title: On demand t-shirt printing.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4d555d'
    - '#8c9dad'
    - '#171a20'
    - '#c0c9d5'
    - '#914858'
  brandStrength: 0.2571908487007022
  lightness: 0.7487832824699581
  saturation: 0.5157996728084981
  rhythmicContrast: 0.2914656805805862
purpose: []
