layout_spectrum: 0.9339640869293362
typography_spectrum: 0.5009334702044725
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.04065362620167434
  lightness: 0.046757074538618326
  saturation: 0.9665115752723068
  rhythmicContrast: 0.13331395597197115
content_rating:
  adult: false
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: John De Mello
  email: ''
  url: ''
logo: null
name: "\_DTGworks"
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/bbeedef5-d7a5-4a40-9055-2d98f523bfe6.jpg
title: ''
description: CUSTOM PRINTING ON DEMAND
purpose: []
