typography_spectrum: 0.9032109549734741
content_rating:
  adult: false
color:
  brandColors:
    - '#E6E2AF'
    - '#A7A37E'
    - '#EFECCA'
    - '#046380'
    - '#002F2F'
  brandStrength: 0.004459558054804802
  lightness: 0.3964458180125803
  saturation: 0.789158075582236
  rhythmicContrast: 0.5566379430238158
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.5943646025843918
analytics:
  google: null
  facebook: null
  twitter: null
logo: null
name: 'DTG works '
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/bbeedef5-d7a5-4a40-9055-2d98f523bfe6.jpg
title: ''
purpose: []
