layout_spectrum: 0.9339640869293362
typography_spectrum: 0.9537143621128052
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.5044688521884382
  lightness: 0.5962394778616726
  saturation: 0.29518753639422357
  rhythmicContrast: 0.28241901844739914
content_rating:
  adult: false
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: John De Mello
  email: ''
  url: ''
logo: null
name: "\_DTGworks"
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/bbeedef5-d7a5-4a40-9055-2d98f523bfe6.jpg
title: ''
description: CUSTOM PRINTING ON DEMAND
purpose: []
