name: DTG works
favicon: null
layout_spectrum: 1
typography_spectrum: 0.05445
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4d555d'
    - '#8c9dad'
    - '#171a20'
    - '#c0c9d5'
    - '#914858'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
